[package]
name = "mini-kv"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = {version = "1.0.89", features = ["derive"]}
serde_repr = "0.1"
bincode = "1.3.3"
