[package]
name = "axume_03_user_manage"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.5.13"
tokio = {version = "1.0", features = ["full"]}
serde = { version = "1.0.130", features = ["derive"] }
